// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace course_manager.Models
{
    public partial class Course
    {
        public Course()
        {
            Assignments = new HashSet<Assignment>();
            StudentsCourses = new HashSet<StudentsCourse>();
        }

        public int CourseId { get; set; }
        public int TeacherId { get; set; }
        public string CourseName { get; set; }
        public string CourseDescription { get; set; }
        public int? CourseCredits { get; set; }

        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<StudentsCourse> StudentsCourses { get; set; }
    }
}