// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace course_manager.Models
{
    public partial class StudentsCourse
    {
        public int StudentsCoursesId { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }

        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public int StudentCoursesId { get; internal set; }
    }
}