// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace course_manager.Models
{
    public partial class Student
    {
        public Student()
        {
            Assignments = new HashSet<Assignment>();
            StudentsCourses = new HashSet<StudentsCourse>();
        }

        public int StudentId { get; set; }
        public string StudentFirstname { get; set; }
        public string StudentLastname { get; set; }
        public string StudentEmail { get; set; }
        public string StudentPhone { get; set; }

        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<StudentsCourse> StudentsCourses { get; set; }
    }
}